### ISSUE TITLE
Rethink bumping strategy for subversions

### ISSUE THREAD

**Issue by viviag** [GetShopTV/changelogged#50]
Stamp tag, upload it and print link.
Problems: authentication and release notes. Maybe it's better to leave release on hands of maintaner.

**Comment by fizruk** [comment]
There are other tools to actually manage GitHub releases, see e.g. https://deeeet.com/ghr/

We can still point people to those tools somewhere in the documentation.

**Comment by viviag** [comment]
I just don't like that we have different strategy for subversions. If one bumps general version twice together result will be same as if once. But we probably should bump subversions in indicator files. It must be at least more verbose by default.

**Comment by viviag** [comment]
It's not a problem more since we are stamping tags to changelogs. On second trial user will fail to bump will `apparently doesn't contain new entries` message regardless of current version source.
