### ISSUE TITLE
Print out inferred info about the project

### ISSUE THREAD

**Issue by fizruk** [GetShopTV/changelogged#67]
- [x] current project version(s)
- [x] changelog filepath(s)
- [ ] project type (do we default to a Haskell Cabal project now?)
- [x] Git hosting type (we only handle GitHub for now, right?)
- [ ] anything else

**Comment by viviag** [comment]
We default to Haskell Stack >= 1.6.0 project with hpack.
And we handle any Git hosting type supporting term "pull request" and numbering like _#d+_. Seems that only Github.

**Comment by viviag** [comment]
Closing for now since I have no idea how could one know project type from changelog manager.
It could be used as interface to things known to git. As it seems to used properly for now.
