### ISSUE TITLE
Manage ignored changes

### ISSUE THREAD

**Issue by fizruk** [GetShopTV/changelogged#70]
Some changes are not worthy of being mentioned in a CHANGELOG. Some of them are changelog changes and version bumps. Others might be minor documentation tweaks or small refactoring.

We need a way to ignore
- changes to certain files (this can be some in `changelogged.yaml`);
- specific commits and/or pull requests (this can clutter `changelogged.yaml`, so I think there can be a separate file for a list of ignored commits).

**Comment by viviag** [comment]
Now we ignore all `.md` files by default. I don't believe in any general way to ignore version bumps (just by commit message). So i propose to leave current behavior as default (maybe adding new ignored extensions or list of other ignored files in `changelogged.yaml`). And solve #71 with full customization.
